# Generated by Django 3.0.8 on 2020-08-02 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200802_0314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cover_image',
            new_name='image',
        ),
    ]
